### ISSUE TITLE
🗺️ Ubicar puntos clave

### ISSUE THREAD

**Issue by anattolia** [enflujo/070-cra7#1]
¿Cómo ubicar los puntos clave en relación a la gran imagen y a la longitud horizontal de la página?

En los datos estoy sacando coordenadas y direcciones pero en realidad no quieren usar mapa, entonces quizás no sirven de nada las coordenadas. Hay que inventar un sistema.
¿Quizás dividir la imagen horizontalmente en N partes y ubicar los puntos clave en esa grilla?

**Comment by 1cgonza** [comment]
> ¿Quizás dividir la imagen horizontalmente en N partes y ubicar los puntos clave en esa grilla?

Sí, aunque, las calles no siempre saltan de número en distancias iguales, entonces no se puede dividir esa grilla horizontal en N partes iguales y usar los números de la dirección. Tienes razón que las direcciones y coordenadas no son útiles para hacer cálculos en el código.

Se me ocurre una estructura así:

```js
const seccion1 = {
  rutaImg: '/imgs/seccion1.webp',
  anchoImg: 2000px,
  altoImg: 1400px,
  puntos: [
    { x1: 800, x2: 950, titulo: 'ruido calle 56', ...otrosDatosQueSeNecesitenPorPunto },
    { x1: 850, x2: 1030, titulo: 'ruido calle 100', ...otrosDatosQueSeNecesitenPorPunto },
  ]
}
```

Entonces, el ancho original de la imagen lo sabemos de antemano y podemos ubicar puntos en relación a las dimensiones de esa imagen. Luego en la página, si escalamos esa imagen original a otro tamaño, podemos saber dónde van los puntos porque escalamos los valores de `x1` y `x2` la misma proporción que escalamos la imagen original. 

Voy a dejar estas funciones por acá que luego sirven para hacer ese tipo de cálculos de pixeles a porcentaje y de porcentaje a pixeles.  

```js
const porcentaje = (seccion: number, total: number) => {
  return (seccion / total) * 100;
};

const pixelesDePorcentaje = (porcentaje: number, total: number) => {
  return (porcentaje / 100) * total;
};
```
