### ISSUE TITLE
:question: Los puntos no tienen un mismo sistema de referencia

### ISSUE THREAD

**Issue by 1cgonza** [enflujo/070-cra7#10]
Hasta donde veo, en ruido por ejemplo se usa 'Punto muestreado'  y 'Name', por ejemplo 

| Punto muestreado    |      Name      |  
|----------|:-------------:|
| 1 |  7ma-37 | 

En Mapa 7ma se llaman **tramos** que en este caso, el más cercano sería: _calle 36_

¿Cuál sería la forma de saber donde va cada cosa?

**Comment by anattolia** [comment]
Podemos cambiar los puntos en el otro excel para que coincidan con los puntos en los que se hicieron mediciones

**Comment by 1cgonza** [comment]
Ya definimos esto y la fuente de verdad va a ser lo documentado en: 2bc7184784d15259bc6b672de2601166e7c4f769
